### ISSUE TITLE
BackupFilewithPeriod this function ise used incorrectly

### ISSUE THREAD

**Issue by akdilsiz** [barisaydogdu/FileBackupToolCLI#1]
https://github.com/barisaydogdu/FileBackupToolCLI/blob/0d4c039e60bba7cd4b6f4dff416f5e996c01d8bb/pkg/file/file.go#L12C6-L12C26

You would achieve a better and smoother result by using the **time.Ticker** here.

**Comment by akdilsiz** [comment]
@barisaydogdu What do you think about the subject I mentioned? You haven't answered yet.

**Comment by barisaydogdu** [comment]
Thank you very much for your comment. I apologize for the late reply. Using time.Tickers will be a great improvement for the performance of the project. I will push the code edited as Time.tickers as soon as possible 🚀

**Comment by barisaydogdu** [comment]
> https://github.com/barisaydogdu/FileBackupToolCLI/blob/0d4c039e60bba7cd4b6f4dff416f5e996c01d8bb/pkg/file/file.go#L12C6-L12C26
> 
> You would achieve a better and smoother result by using the **time.Ticker** here.


https://github.com/barisaydogdu/FileBackupToolCLI/blob/348ac1c0d6785adc733bce166c9c65ea2d1db8c5/pkg/file/file.go#L12


I used the time.Ticker structure within the BackupFilewithPeriod function to implement a periodic backup process. I have committed this update to the code. Thank you again for your suggestion.

**Comment by akdilsiz** [comment]
@barisaydogdu #2 can you review this pr?

**Comment by barisaydogdu** [comment]
> @barisaydogdu #2 can you review this pr?

I reviewed your PR and learned a lot from the improvements you made to enhance code quality, which also gave me a new perspective. Also this helped me better understand the context structure. Thank you for your valuable contributions.
